server:
  port: 8081
  servlet:
    context-path: /Translate
# 引入 数据库的相关配置
spring:
  # 配置thymeleaf的相关信息
  thymeleaf:
    # 开启视图解析
    enabled: true
    #编码格式
    encoding: UTF-8
    #前缀配置
    prefix: classpath:/templates/
    # 后缀配置
    suffix: .html
    #是否使用缓存 开发环境时不设置缓存
    cache: false
    # 格式为 HTML 格式
    mode: HTML5
    # 配置类型
    servlet:
      content-type: text/html
# 配置翻译的相关的信息
yd:
  appId: 6df865c49605b6e0
  securityKey: mCRQ8UxtNQ1hDLx9CAuoBhqKwEh0mS5Z
bd:
  appId: 20180525000166607
  securityKey: X3MD2XTQjUG7XjB8MKoe