server:
  port: 8082
# 设置保存二维码的目录
qrcode:
  saveDir: D:\\githubBoot\\Function\\Qrcode
  logoPath: D:\\githubBoot\\Function\\Qrcode\\logo.jpg
  parseDir: D:\\githubBoot\\Function\\Qrcode

# javamelody 监控
javamelody:
  # 启用JavaMelody自动配置（可选，默认值：true）
  enabled: true
  # 要从监视中排除的数据源名称（可选，以逗号分隔）
  #  excluded-datasources: secretSource,topSecretSource
  # 启用对Spring服务和控制器的监视（可选，默认值：true）
  spring-monitoring-enabled: true
  # JavaMelody的初始化参数（可选）
  # See: https://github.com/javamelody/javamelody/wiki/UserGuide#6-optional-parameters
  init-parameters:
    # 记录http请求
    log: true
    # 从监视中排除图像，css，字体和js网址
    url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # 汇总http请求中的数字
    #http-transform-pattern: \d+
    # 添加基本身份验证
    # authorized-users: admin:{SHA-256}6ca13d52ca70c883e0f0bb101e425a89e8624de51db2d2392593af6a84118090
    authorized-users: admin:abc123
    # 更改默认存储目录：
    #storage-directory: /tmp/javamelody
    # 更改默认的“ / monitoring”路径：
    #monitoring-path: /admin/performance